import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const tools = process.argv[2] === "tools";

const external = [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
];

// The checks and the vault report run in Node, so the Obsidian API is replaced
// by a stub: the plugin code under test is the same file that ships.
if (tools) {
    const shared = {
        bundle: true,
        platform: "node",
        alias: { obsidian: "./tools/obsidian-stub.ts" },
        // ESM: the checks read as straight-line code with await at the top level.
        format: "esm",
        target: "node20",
        logLevel: "warning",
        treeShaking: true,
    };
    await esbuild.build({ ...shared, entryPoints: ["tools/cases.ts"], outfile: ".cache/tools/cases.mjs" });
    await esbuild.build({ ...shared, entryPoints: ["tools/vault-report.ts"], outfile: ".cache/tools/vault-report.mjs" });
    await esbuild.build({ ...shared, entryPoints: ["tools/vault-dry-run.ts"], outfile: ".cache/tools/vault-dry-run.mjs" });
    process.exit(0);
}

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external,
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
